services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - DATABASE=${DATABASE}
      - COLLECTION=${COLLECTION}
      - COLLECTION_INFO=${COLLECTION_INFO}
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo_data:/data/db
      - ./mongo/mongo_init/init_mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/mongo_init/create_users.js:/docker-entrypoint-initdb.d/create-users.js:ro

  python-csv:
    build:
      context: ./python-csv # localisation du dockerfile pour la construction de l'image
    container_name: python-csv
    env_file:
      - .env
    depends_on:
      - mongo  # Vérifie que le conteneur de la base mongo est bien lancé
    volumes:
      - ./python-csv:/usr/src/app # monte le directory dans le container
    command: ["python", "main.py"]  # commande lancé dans le container

volumes: {}


